name: Upgrade Requirements

on:
  schedule:
    # will start the job at midnight every monday (UTC)
    - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to run make upgrade in'
        required: true
        default: 'master'
  # just added for testing
  pull_request:
    branches:
      - '**'

jobs:
  upgrade_requirements:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.8' ]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install pip
      run: pip install pip==20.2.4

    - name: make upgrade
      run: |
        cd $GITHUB_WORKSPACE
        make upgrade

    - name: Clone testeng-ci
      run: git clone https://github.com/edx/testeng-ci.git

    - name: setup testeng-ci
      run: |
        ls -a
        cd $GITHUB_WORKSPACE/testeng-ci
        pip install -r requirements/base.txt

    - name: create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_REQUIREMENTS_BOT_TOKEN }}
        GITHUB_USER_EMAIL: ${{ secrets.GITHUB_REQUIREMENTS_BOT_EMAIL }}
      run: |
        ls -a
        cd $GITHUB_WORKSPACE/testeng-ci
        python -m jenkins.pull_request_creator --repo-root=$GITHUB_WORKSPACE \
        --target-branch=${{ github.event.inputs.branch }} --base-branch-name="upgrade-python-requirements" \
        --commit-message="Updating Python Requirements" --pr-title="Python Requirements Update" \
        --pr-body="Python requirements update.  Please review the [changelogs](\https://openedx.atlassian.net/wiki/spaces/TE/pages/1001521320/Python+Package+Changelogs\) for the upgraded packages." \
        --user-reviewers="" --team-reviewers="course-discovery-admins" --delete-old-pull-requests
